---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
        #mass_threshold: 20
  fixme:
    enabled: true
  foodcritic:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/
